-- Create Database
create database QL_HETHONGTHITRACNGHIEM
go 
use QL_HETHONGTHITRACNGHIEM
--================================================================================
-- Create table
GO
CREATE TABLE KHOA
(
	MAKHOA CHAR(2) PRIMARY KEY CONSTRAINT PK_KHOA DEFAULT DBO.AUTO__MAKHOA(),
	TENKHOA NVARCHAR(100) NOT NULL,
	SOLUONGGIANGVIEN INT,
	SOLUONGMONHOC INT,
	SONGANHDAOTAO INT,
)

GO
CREATE TABLE LOPHOC
(
	MALOP CHAR(10) NOT NULL,
	TENLOP NVARCHAR(50),
	SISO INT,
	MAKHOA CHAR(2),

	CONSTRAINT PK_LOPHOC PRIMARY KEY (MALOP),
	CONSTRAINT FK_LOPHOC_KHOA FOREIGN KEY (MAKHOA) REFERENCES KHOA(MAKHOA),
)

GO
CREATE TABLE HOCPHAN
(
	MAHOCPHAN CHAR(10) NOT NULL,
	TENHOCPHAN NVARCHAR(100),
	SOTC INT,
	SOTIET_LT INT,
	SOTIET_TH INT,
	MAKHOA CHAR(2),

	CONSTRAINT PK_HOCPHAN PRIMARY KEY (MAHOCPHAN),
	CONSTRAINT FK_HOCPHAN_KHOA FOREIGN KEY (MAKHOA) REFERENCES KHOA(MAKHOA),
)

GO
CREATE TABLE SINHVIEN
(
	MASV CHAR(10) NOT NULL,
	MAKHAU CHAR(20),
	TENSV NVARCHAR(50),
	GIOITINH NVARCHAR(5),
	NGAYSINH DATE,
	EMAIL NVARCHAR(100),
	SDT CHAR(10),
	DIACHI NVARCHAR(100),
	QUEQUAN NVARCHAR(100),
	MALOP CHAR(10),
	HOCPHI NVARCHAR(10),

	CONSTRAINT PK_SINHVIEN PRIMARY KEY (MASV),
	CONSTRAINT FK_SINHVIEN_LOPHOC FOREIGN KEY (MALOP) REFERENCES LOPHOC(MALOP),
)

GO 
CREATE TABLE CT_HOCPHAN
(
	MALOPHOCPHAN CHAR(12) NOT NULL,
	MASV CHAR(10) NOT NULL,
	MAHOCPHAN CHAR(10) NOT NULL,
	MAGV CHAR(10),
	THU INT,
	TIET CHAR(10),
	PHONG CHAR(10),
	NGAYBD DATE,
	NGAYKT DATE,

	CONSTRAINT PK_CT_HOCPHAN PRIMARY KEY (MALOPHOCPHAN, MASV, MAHOCPHAN),
	CONSTRAINT FK_CT_HOCPHAN_SINHVIEN FOREIGN KEY (MASV) REFERENCES SINHVIEN(MASV),
	CONSTRAINT FK_CT_HOCPHAN_HOCPHAN FOREIGN KEY (MAHOCPHAN) REFERENCES HOCPHAN(MAHOCPHAN),
)

GO 
CREATE TABLE CHUCVU
(
	MACHUCVU INT NOT NULL IDENTITY(1,1),
	TENCHUCVU NVARCHAR(100),

	CONSTRAINT PK_CHUCVU PRIMARY KEY (MACHUCVU),
)

GO
CREATE TABLE GIANGVIEN
(
	MAGV CHAR(10) NOT NULL,
	MATKHAU CHAR(20),
	TENGV NVARCHAR(50),
	NGAYSINH DATE,
	GIOITINH NVARCHAR(5),
	QUEQUAN NVARCHAR(20),
	HOCVI NVARCHAR(50),
	SDT CHAR(10),
	EMAIL NVARCHAR(100),
	DIACHI NVARCHAR(100),
	AVATA IMAGE,
	MAKHOA CHAR(2),
	MACHUCVU INT,

	CONSTRAINT PK_GIANGVIEN PRIMARY KEY (MAGV),
	CONSTRAINT FK_GIANGVIEN_KHOA FOREIGN KEY (MAKHOA) REFERENCES KHOA(MAKHOA),
	CONSTRAINT FK_GIANGVIEN_CHUCVU FOREIGN KEY (MACHUCVU) REFERENCES CHUCVU(MACHUCVU),
)

GO
CREATE TABLE CT_GIANGDAY
(
	MAHOCPHAN CHAR(10) NOT NULL,
	MAGV CHAR(10) NOT NULL,

	CONSTRAINT PK_CT_GIANGDAY PRIMARY KEY (MAHOCPHAN, MAGV),
	CONSTRAINT FK_CT_GIANGDAY_HOCPHAN FOREIGN KEY (MAHOCPHAN) REFERENCES HOCPHAN(MAHOCPHAN),
	CONSTRAINT FK_CT_GIANGDAY_GIANGVIEN FOREIGN KEY (MAGV) REFERENCES GIANGVIEN(MAGV),
)

GO
CREATE TABLE NGANHANGCAUHOI
(
	MANGANHANG INT IDENTITY(1,1) NOT NULL,
	SLCAUHOI INT,
	NGAYTAO DATE,
	NGAYCAPNHAT DATE,

	CONSTRAINT PK_NGANHANGCAUHOI PRIMARY KEY (MANGANHANG),
)

GO
CREATE TABLE CT_NGANHANGCAUHOI
(
	MANGANHANG INT NOT NULL,
	MAGV CHAR(10) NOT NULL,
	MAHOCPHAN CHAR(10) NOT NULL,

	CONSTRAINT PK_CT_NGANHANGCAUHOI PRIMARY KEY (MANGANHANG, MAGV, MAHOCPHAN),
	CONSTRAINT FK_NGANHANGCAUHOI_NGANHANGCAUHOI FOREIGN KEY (MANGANHANG) REFERENCES NGANHANGCAUHOI(MANGANHANG),
	CONSTRAINT FK_NGANHANGCAUHOI_GIANGVIEN FOREIGN KEY (MAGV) REFERENCES GIANGVIEN(MAGV),
	CONSTRAINT FK_NGANHANGCAUHOI_HOCPHAN FOREIGN KEY (MAHOCPHAN) REFERENCES HOCPHAN(MAHOCPHAN),
)

GO
CREATE TABLE CAUHOI
(
	MACAUHOI INT NOT NULL IDENTITY(1,1),
	NOIDUNG NVARCHAR(MAX),
	DAPAN1 NVARCHAR(MAX),
	DAPAN2 NVARCHAR(MAX),
	DAPAN3 NVARCHAR(MAX),
	DAPAN4 NVARCHAR(MAX),
	DAPANDUNG CHAR(5),
	NGAYTAO DATE,
	NGAYCAPNHAT DATE,
	MANGANHANG INT,
	MAHOCPHAN CHAR(10)

	CONSTRAINT PK_CAUHOI PRIMARY KEY (MACAUHOI),
	CONSTRAINT FK_CAUHOI_NGANHANGCAUHOI FOREIGN KEY (MANGANHANG) REFERENCES NGANHANGCAUHOI(MANGANHANG),
	CONSTRAINT FK_CAUHOI_MAHOCPHAN FOREIGN KEY (MAHOCPHAN) REFERENCES HOCPHAN(MAHOCPHAN),
)

GO
CREATE TABLE DETHI
(
	MADETHI INT IDENTITY(1, 1),
	MAHOCPHAN CHAR(10),
	NGAYTAO DATE,
	TGLAMBAI INT,
	SLCAUHOI INT,
	TINHTRANG BIT,

	CONSTRAINT PK_DETHI PRIMARY KEY (MADETHI),
	CONSTRAINT FK_DETHI_HOCPHAN FOREIGN KEY (MAHOCPHAN) REFERENCES HOCPHAN(MAHOCPHAN),
)

GO 
CREATE TABLE CT_DETHI
(
	STT INT IDENTITY(1, 1),
	MADETHI INT,
	MADECON CHAR(10),
	MACAUHOI INT,

	CONSTRAINT PK_CT_DETHI PRIMARY KEY (STT),
	CONSTRAINT FK_CT_DETHI_DETHI FOREIGN KEY (MADETHI) REFERENCES DETHI(MADETHI),
	CONSTRAINT FK_CT_DETHI_CAUHOI FOREIGN KEY (MACAUHOI) REFERENCES CAUHOI(MACAUHOI),
)

GO
CREATE TABLE NGANHANGCAUHOI_DADUYET
(
	MANH CHAR(10) NOT NULL,
	MAHOCPHAN CHAR(10) NOT NULL,
	MACAUHOI INT NOT NULL,

	CONSTRAINT PK_NGANHANGCAUHOI_DADUYET PRIMARY KEY (MANH, MAHOCPHAN, MACAUHOI),
	CONSTRAINT FK_NGANHANGCAUHOI_DADUYET_HOCPHAN FOREIGN KEY (MAHOCPHAN) REFERENCES HOCPHAN(MAHOCPHAN),
	CONSTRAINT FK_NGANHANGCAUHOI_DADUYET_CAUHOI FOREIGN KEY (MACAUHOI) REFERENCES CAUHOI(MACAUHOI),
)

GO
CREATE TABLE CATHI
(
	MACATHI INT IDENTITY(1,1) NOT NULL,
	MAHOCPHAN CHAR(10),
	MADETHI INT,
	MADECON NVARCHAR(10),
	NGAYTHI DATE,
	PHONGTHI NVARCHAR(20),
	GIOLAMBAI NVARCHAR(10),
	TINHTRANG BIT,
	TINHTRANGTHI BIT,

	CONSTRAINT PK_CATHI PRIMARY KEY (MACATHI),
	CONSTRAINT FK_CATHI_HOCPHAN FOREIGN KEY (MAHOCPHAN) REFERENCES HOCPHAN(MAHOCPHAN),
	CONSTRAINT FK_CATHI_DETHI FOREIGN KEY (MADETHI) REFERENCES DETHI(MADETHI),
)

GO
CREATE TABLE CT_CATHI
(
	MACATHI INT NOT NULL,
	MASV CHAR(10) NOT NULL,
	TENSV NVARCHAR(MAX),

	CONSTRAINT PK_CT_CATHI PRIMARY KEY (MACATHI, MASV),
	CONSTRAINT FK_CT_CATHI_CATHI FOREIGN KEY (MACATHI) REFERENCES CATHI(MACATHI),
	CONSTRAINT FK_CT_CATHI_SINHVIEN FOREIGN KEY (MASV) REFERENCES SINHVIEN(MASV),
)

GO
CREATE TABLE BAITHI
(
	MABAITHI INT IDENTITY(1,1) NOT NULL,
	GIONOPBAI NVARCHAR(50),
	DIEM INT,
	MASV CHAR(10),
	TINHTRANG NVARCHAR(20), -- ĐANG LÀM - ĐÃ NỘP
	MACATHI INT,

	CONSTRAINT PK_BAITHI PRIMARY KEY (MABAITHI),
	--CONSTRAINT FK_BAITHI_SINHVIEN FOREIGN KEY (MASV) REFERENCES SINHVIEN(MASV),
	--CONSTRAINT FK_BAITHI_CATHI FOREIGN KEY (MACATHI) REFERENCES CATHI(MACATHI),
)

GO
CREATE TABLE CT_BAITHI
(
	MABAITHI INT NOT NULL,
	MACAUHOI INT NOT NULL,
	CAUTRALOI CHAR(5),

	CONSTRAINT PK_CT_BAITHI PRIMARY KEY (MABAITHI, MACAUHOI),
	--CONSTRAINT FK_CT_BAITHI_BAITHI FOREIGN KEY (MABAITHI) REFERENCES BAITHI(MABAITHI),
	--CONSTRAINT FK_CT_BAITHI_CAUHOI FOREIGN KEY (MACAUHOI) REFERENCES CAUHOI(MACAUHOI),
)

-- ===================================================================================================

-- ===================================================================================================
-- TRIGGER UPDATE QUANTITY QUESTION IN NGANHANGCAUHOI WHEN INSERT QUESTION 

-- ===================================================================================================

-- ===================================================================================================

-- ===================================================================================================

-- ===================================================================================================
-- INSERT VALUES ----- CHUCVU
SELECT *FROM CHUCVU
INSERT INTO CHUCVU(TENCHUCVU) VALUES (N'TRƯỞNG KHOA')
INSERT INTO CHUCVU(TENCHUCVU) VALUES (N'NHÂN VIÊN PHÒNG KHẢO THÍ')
INSERT INTO CHUCVU(TENCHUCVU) VALUES (N'NHÂN VIÊN PHÒNG ĐÀO TẠO')
INSERT INTO CHUCVU(TENCHUCVU) VALUES (N'GIẢNG VIÊN BỘ MÔN')

-- INSERT VALEUS ----- KHOA
SELECT *FROM KHOA
INSERT INTO KHOA(TENKHOA) VALUES (N'KHOA CÔNG NGHỆ THÔNG TIN')
INSERT INTO KHOA(TENKHOA) VALUES (N'KHOA CÔNG NGHỆ ĐIỆN - ĐIỆN TỬ')
INSERT INTO KHOA(TENKHOA) VALUES (N'KHOA TÀI CHÍNH KẾ TOÁN')
INSERT INTO KHOA(TENKHOA) VALUES (N'KHOA CÔNG NGHỆ CƠ KHÍ')
INSERT INTO KHOA(TENKHOA) VALUES (N'KHOA CHÍNH TRỊ - LUẬT')
INSERT INTO KHOA(TENKHOA) VALUES (N'KHOA CÔNG NGHỆ SINH HỌC')
INSERT INTO KHOA(TENKHOA) VALUES (N'KHOA DU LỊCH VÀ ẨM THỰC')
INSERT INTO KHOA(TENKHOA) VALUES (N'KHOA QUẢN TRỊ KINH DOANH')
INSERT INTO KHOA(TENKHOA) VALUES (N'KHOA GIÁO DỤC THỂ CHẤT VÀ QUỐC PHÒNG AN NINH')
INSERT INTO KHOA(TENKHOA) VALUES (N'KHOA NGOẠI NGỮ')
INSERT INTO KHOA(TENKHOA) VALUES (N'CÔNG NGHỆ MAY VÀ THỜI TRANG')
INSERT INTO KHOA(TENKHOA) VALUES (N'KHOA CÔNG NGHỆ HÓA HỌC')
INSERT INTO KHOA(TENKHOA) VALUES (N'KHOA KHOA HỌC ỨNG DỤNG')
INSERT INTO KHOA(TENKHOA) VALUES (N'KHOA THỦY SẢN')
INSERT INTO KHOA(TENKHOA) VALUES (N'KHOA SINH HỌC VÀ MÔI TRƯỜNG')
INSERT INTO KHOA(TENKHOA) VALUES (N'KHOA CÔNG NGHỆ THỰC PHẨM')

-- INSERT VALUES ----- GIANGVIEN
SELECT *FROM GIANGVIEN
SET DATEFORMAT DMY INSERT INTO GIANGVIEN
VALUES ((SELECT DBO.AUTO_MAGV('010', '01')), '000000000', N'LÂM THỊ HỌA MI', '10/10/1985', N'NỮ', N'**', N'THẠC SĨ', '0654321987', N'milth@hufi.edu.vn', N'......', '', '01', '1')
SET DATEFORMAT DMY INSERT INTO GIANGVIEN
VALUES ((SELECT DBO.AUTO_MAGV('010', '01')), '000000000', N'NGUYỄN THỊ ĐỊNH', '10/10/1985', N'NỮ', N'**', N'THẠC SĨ', '0654321987', N'dinhnt@hufi.edu.vn', N'......', '', '01', '4')

SELECT *FROM KHOA
-- INSERT VALUES ----- LOPHOC
SELECT *FROM LOPHOC
INSERT INTO LOPHOC VALUES ('10DHTH5', N'10 ĐẠI HỌC TIN HỌC 5', '', '01')
INSERT INTO LOPHOC VALUES ('10DHTH2', N'10 ĐẠI HỌC TIN HỌC 2', '', '01')
INSERT INTO LOPHOC VALUES ('10DHTH3', N'10 ĐẠI HỌC TIN HỌC 3', '', '01')
INSERT INTO LOPHOC VALUES ('10DHTH1', N'10 ĐẠI HỌC TIN HỌC 1', '', '01')

-- INSERT VALUES ----- HOCPHAN
SELECT *FROM HOCPHAN
INSERT INTO HOCPHAN VALUES ((SELECT DBO.AUTO_MAHOCPHAN()), N'CẤU TRÚC DỮ LIỆU & GIẢI THUẬT', 3, 45, 30, '01')
INSERT INTO HOCPHAN VALUES ((SELECT DBO.AUTO_MAHOCPHAN()), N'CƠ SỞ DỮ LIỆU', 3, 45, 30, '01')
INSERT INTO HOCPHAN VALUES ((SELECT DBO.AUTO_MAHOCPHAN()), N'ĐẠI SỐ TUYẾN TÍNH', 3, 45, 30, '01')
INSERT INTO HOCPHAN VALUES ((SELECT DBO.AUTO_MAHOCPHAN()), N'CÔNG NGHỆ .NET', 3, 45, 30, '01')
INSERT INTO HOCPHAN VALUES ((SELECT DBO.AUTO_MAHOCPHAN()), N'NO.SQL', 3, 45, 30, '01')

-- INSERT VALUES ----- SINHVIEN
SELECT *FROM SINHVIEN
SET DATEFORMAT DMY INSERT INTO SINHVIEN 
VALUES ((SELECT DBO.AUTO_STT_MASV('20', '01', '19')), '0000000000', N'PHẠM TUẤN ĐẠT', N'NAM', '16/07/2001', N'dat16072001@gmail.com', '0654321987', N'...', N'...', '10DHTH5','')
SET DATEFORMAT DMY INSERT INTO SINHVIEN 
VALUES ((SELECT DBO.AUTO_STT_MASV('20', '01', '19')), '0000000000', N'NGUYỄN VĂN MĂNG', N'NỮ', '16/07/2001', N'...', '...', N'...', N'...', '10DHTH2','')

-- INSERT VALUES ----- CT_HOCPHAN
-- KHI INSERT INTO -> GỌI FUNCTION ĐỂ TẠO MÃ HỌC PHẦN
SELECT *FROM CT_HOCPHAN
SET DATEFORMAT DMY INSERT INTO CT_HOCPHAN 
VALUES ((SELECT DBO.AUTO_MALOPHOCPHAN('0101000004')), '2001190001', '0101000004', '01001001', 2, '1-3', N'A101', '15/11/2022', '15/02/2023')
SET DATEFORMAT DMY INSERT INTO CT_HOCPHAN 
VALUES ((SELECT DBO.AUTO_MALOPHOCPHAN('0101000004')), '2001190001', '0101000004', '01001001', 2, '1-3', N'A102', '15/11/2022', '15/02/2023')

-- INSERT VALUES ----- CT_GIANGDAY
SELECT *FROM CT_GIANGDAY
INSERT INTO CT_GIANGDAY VALUES ('0101000004', '01001001')
INSERT INTO CT_GIANGDAY VALUES ('0101000001', '01001001')
INSERT INTO CT_GIANGDAY VALUES ('0101000002', '01001001')
INSERT INTO CT_GIANGDAY VALUES ('0101000003', '01001001')
INSERT INTO CT_GIANGDAY VALUES ('0101000005', '01001001')
INSERT INTO CT_GIANGDAY VALUES ('0101000004', '01001002')

-- INSERT VALUES ----- NGANHANGCAUHOI
SELECT *FROM NGANHANGCAUHOI
SET DATEFORMAT DMY 
INSERT INTO NGANHANGCAUHOI(NGAYTAO, NGAYCAPNHAT) VALUES ('11/07/2022', '25/07/2022')
SET DATEFORMAT DMY 
INSERT INTO NGANHANGCAUHOI(NGAYTAO, NGAYCAPNHAT) VALUES ('11/07/2022', '25/07/2022')

-- INSERT VALUES ----- CT_NGANHANGCAUHOI
SELECT *FROM CT_NGANHANGCAUHOI
INSERT INTO CT_NGANHANGCAUHOI VALUES (1, '01001001', '0101000004')
INSERT INTO CT_NGANHANGCAUHOI VALUES (1, '01001001', '0101000001')
INSERT INTO CT_NGANHANGCAUHOI VALUES (1, '01001001', '0101000002')
INSERT INTO CT_NGANHANGCAUHOI VALUES (2, '01001002', '0101000002')
INSERT INTO CT_NGANHANGCAUHOI VALUES (2, '01001002', '0101000004')

-- INSERT VALUES ----- CAUHOI
SELECT *FROM CAUHOI
INSERT INTO CAUHOI(NOIDUNG, DAPAN1, DAPAN2, DAPAN3, DAPAN4, DAPANDUNG, MANGANHANG) 
VALUES (N'...', N'...', N'...', N'...', N'...', N'...', 1)

-- INSERT VALUES ----- DETHI
SELECT *FROM DETHI
SET DATEFORMAT DMY INSERT INTO DETHI
VALUES (1, '0101000004', '11/07/2022', 60, 45, 0)
SET DATEFORMAT DMY INSERT INTO DETHI
VALUES (2, '0101000004', '11/07/2022', 60, 45, 0)

-- INSERT VALUES ----- CT_DETHI
SELECT *FROM CT_DETHI
INSERT INTO CT_DETHI VALUES (1, 1, '0101000004')
INSERT INTO CT_DETHI VALUES (1, 2, '0101000004')
INSERT INTO CT_DETHI VALUES (1, 3, '0101000004')

-- INSERT VALUES ----- NGANHANGCAUHOI_DADUYET
SELECT *FROM NGANHANGCAUHOI_DADUYET
INSERT INTO NGANHANGCAUHOI_DADUYET VALUES ('0101000004', 1)
INSERT INTO NGANHANGCAUHOI_DADUYET VALUES ('0101000004', 2)
INSERT INTO NGANHANGCAUHOI_DADUYET VALUES ('0101000004', 3)

-- INSERT VALUES ----- CATHI
SELECT *FROM CATHI
SET DATEFORMAT DMY INSERT INTO CATHI(MAHOCPHAN, MADETHI, NGAYTHI, GIOLAMBAI, TINHTRANG)
VALUES ('0101000004', 1, '11/07/2022', '9:30', 0)
SET DATEFORMAT DMY INSERT INTO CATHI(MAHOCPHAN, MADETHI, NGAYTHI, GIOLAMBAI, TINHTRANG)
VALUES ('0101000004', 2, '11/07/2022', '9:30', 0)

-- INSERT VALUES ----- CT_CATHI
SELECT *FROM CT_CATHI
INSERT INTO CT_CATHI VALUES (1, '2001190001')
INSERT INTO CT_CATHI VALUES (1, '2001190002')

-- INSERT VALUES ----- BAITHI
SELECT *FROM BAITHI
INSERT INTO BAITHI(GIONOPBAI, DIEM, MASV, MABAITHI) 
VALUES ('10:30', 10, '2001190001', 1)
INSERT INTO BAITHI(GIONOPBAI, DIEM, MASV, MABAITHI) 
VALUES ('10:25', 9.5, '2001190002', 1)

-- INSERT VALUES ----- CT_BAITHI
SELECT *FROM CT_BAITHI
INSERT INTO CT_BAITHI VALUES (1, 1, 'A')
INSERT INTO CT_BAITHI VALUES (1, 2, 'B')
INSERT INTO CT_BAITHI VALUES (1, 3, 'B')


-- ===================================================================================================

-- ===================================================================================================