-- CREATE FUNCTION GENERATE MAKHOA
GO
CREATE FUNCTION AUTO__MAKHOA()
RETURNS VARCHAR(2)
AS
BEGIN
	DECLARE @MAKHOA VARCHAR(2)
	IF (SELECT COUNT(MAKHOA) FROM KHOA) = 0
		SET @MAKHOA = '0'
	ELSE
		SELECT @MAKHOA = MAX(RIGHT(MAKHOA, 2)) FROM KHOA
		SELECT @MAKHOA = CASE 
			WHEN @MAKHOA >= 0 AND @MAKHOA < 9 THEN '0' + CONVERT(CHAR, CONVERT(INT, @MAKHOA) + 1)
			WHEN @MAKHOA >= 9 THEN '' + CONVERT(CHAR, CONVERT(INT, @MAKHOA) + 1)
		END
	RETURN @MAKHOA
END
GO
---------------------------------------------------------
-- CREATE FUNCTION GENERATE STT GIANGVIEN -> ADD PRAMETER
GO
CREATE FUNCTION AUTO_MAGV(@DAU CHAR(3), @MAKHOA CHAR(2))
RETURNS CHAR(8)
AS
BEGIN
	DECLARE @MAGV VARCHAR(8)
	IF (SELECT COUNT(MAGV) FROM GIANGVIEN) = 0
		SET @MAGV = '0'
	ELSE
		SELECT @MAGV = MAX(RIGHT(RTRIM(MAGV), 3)) FROM GIANGVIEN
		SELECT @MAGV = CASE 
			WHEN @MAGV >= 0 AND @MAGV < 9 THEN @DAU + @MAKHOA + '00' + CONVERT(CHAR, CONVERT(INT, @MAGV) + 1)
			WHEN @MAGV >= 9 AND @MAGV < 99 THEN @DAU + @MAKHOA +  '0' + CONVERT(CHAR, CONVERT(INT, @MAGV) + 1)
			WHEN @MAGV >= 99 THEN @DAU + @MAKHOA +  '' + CONVERT(CHAR, CONVERT(INT, @MAGV) + 1)
		END
	RETURN @MAGV
END
GO
SELECT DBO.AUTO_MAGV('010', '01')

---------------------------------------------------------
-- CREATA FUNCTION GENERATE MASV -> ADD PARAMETER
GO
CREATE FUNCTION AUTO_STT_MASV(@DAIHOC CHAR(2), @MAKHOA CHAR(2), @NAMNHAPHOC CHAR(2))
RETURNS CHAR(10)
AS
BEGIN
	DECLARE @MASV CHAR(10)
	IF (SELECT COUNT(MASV) FROM SINHVIEN) = 0
		SET @MASV = '0'
	ELSE
		SELECT @MASV = MAX(RIGHT(RTRIM(MASV), 4)) FROM SINHVIEN
		SELECT @MASV = CASE 
			WHEN @MASV >= 0 AND @MASV < 9 THEN @DAIHOC + @MAKHOA + @NAMNHAPHOC + '000' + CONVERT(CHAR, CONVERT(INT, @MASV) + 1)
			WHEN @MASV >= 9 AND @MASV < 99 THEN @DAIHOC + @MAKHOA + @NAMNHAPHOC + '00' + CONVERT(CHAR, CONVERT(INT, @MASV) + 1)
			WHEN @MASV >= 99 AND @MASV < 999 THEN @DAIHOC + @MAKHOA + @NAMNHAPHOC + '0' + CONVERT(CHAR, CONVERT(INT, @MASV) + 1)
			WHEN @MASV >= 999 THEN @DAIHOC + @MAKHOA + @NAMNHAPHOC + '' + CONVERT(CHAR, CONVERT(INT, @MASV) + 1)
		END
	RETURN @MASV
END
GO
SELECT DBO.AUTO_STT_MASV('20', '01', '19')

---------------------------------------------------------
-- CREATE FUNCTION GERERATE MAHOCPHAN 
GO
CREATE FUNCTION AUTO_MAHOCPHAN()
RETURNS CHAR(10)
AS
BEGIN
	DECLARE @MAHOCPHAN CHAR(10)
	IF (SELECT COUNT(MAHOCPHAN) FROM HOCPHAN) = 0
		SET @MAHOCPHAN = '0'
	ELSE
		SELECT @MAHOCPHAN = MAX(RIGHT(RTRIM(MAHOCPHAN), 5)) FROM HOCPHAN
		SELECT @MAHOCPHAN = CASE 
			WHEN @MAHOCPHAN >= 0 AND @MAHOCPHAN < 9 THEN '010100000' + CONVERT(CHAR, CONVERT(INT, @MAHOCPHAN) + 1)
			WHEN @MAHOCPHAN >= 9 AND @MAHOCPHAN < 99 THEN '01010000' + CONVERT(CHAR, CONVERT(INT, @MAHOCPHAN) + 1)
			WHEN @MAHOCPHAN >= 99 AND @MAHOCPHAN < 999 THEN '0101000' + CONVERT(CHAR, CONVERT(INT, @MAHOCPHAN) + 1)
			WHEN @MAHOCPHAN >= 999 AND @MAHOCPHAN < 9999 THEN '010100' + CONVERT(CHAR, CONVERT(INT, @MAHOCPHAN) + 1)
			WHEN @MAHOCPHAN >= 9999 AND @MAHOCPHAN < 99999 THEN '01010' + CONVERT(CHAR, CONVERT(INT, @MAHOCPHAN) + 1)
		END
	RETURN @MAHOCPHAN
END
GO
SELECT DBO.AUTO_MAHOCPHAN()

---------------------------------------------------------
-- CREATE FUNCTION GERERATE MALOPHOCPHAN -> ADD PARAMETER @MAHOCPHAN
GO
CREATE FUNCTION AUTO_MALOPHOCPHAN(@MAHOCPHAN CHAR(10))
RETURNS CHAR(12)
AS
BEGIN
	DECLARE @MALOPHOCPHAN CHAR(12)
	IF (SELECT COUNT(MALOPHOCPHAN) FROM CT_HOCPHAN) = 0
		SET @MALOPHOCPHAN = '0'
	ELSE
		SELECT @MALOPHOCPHAN = MAX(RIGHT(RTRIM(MALOPHOCPHAN), 2)) FROM CT_HOCPHAN
		SELECT @MALOPHOCPHAN = CASE 
			WHEN @MALOPHOCPHAN >= 0 AND @MALOPHOCPHAN < 9 THEN @MAHOCPHAN + '0' + CONVERT(CHAR, CONVERT(INT, @MALOPHOCPHAN) + 1)
			WHEN @MALOPHOCPHAN >= 9 THEN @MAHOCPHAN + '' + CONVERT(CHAR, CONVERT(INT, @MALOPHOCPHAN) + 1)
		END
	RETURN @MALOPHOCPHAN
END
GO
SELECT DBO.AUTO_MALOPHOCPHAN('0101000958')