-- CREATE PROC GET_CT_NGANHANGCAUHOI
GO
CREATE PROC GET_CT_NGANHANGCAUHOI @MANGANHANG INT
AS
BEGIN
	SELECT NGANHANGCAUHOI.MANGANHANG, TENHOCPHAN, SLCAUHOI, NGAYTAO, NGAYCAPNHAT, CT_NGANHANGCAUHOI.MAHOCPHAN 
	FROM NGANHANGCAUHOI, CT_NGANHANGCAUHOI, HOCPHAN
	WHERE NGANHANGCAUHOI.MANGANHANG = CT_NGANHANGCAUHOI.MANGANHANG
		AND CT_NGANHANGCAUHOI.MAHOCPHAN = HOCPHAN.MAHOCPHAN
		AND NGANHANGCAUHOI.MANGANHANG = @MANGANHANG
		AND CT_NGANHANGCAUHOI.MAHOCPHAN != '0101000000'
END
GO

-- CREATE PROC GET_DS_CAUHOI_NGANHANG
GO
CREATE PROC GET_DS_CAUHOI_NGANHANG @MANGANHANG INT, @MAHOCPHAN CHAR(10)
AS
BEGIN
	SELECT MACAUHOI, NOIDUNG, DAPAN1, DAPAN2, DAPAN3, DAPAN4, DAPANDUNG, NGAYTAO, NGAYCAPNHAT
	FROM CAUHOI WHERE MANGANHANG = @MANGANHANG AND MAHOCPHAN = @MAHOCPHAN 
					AND MACAUHOI NOT IN (SELECT MACAUHOI FROM NGANHANGCAUHOI_DADUYET WHERE MANH = @MANGANHANG AND MAHOCPHAN = @MAHOCPHAN)
END
GO

-- CREATE PROC GET_DS_MONHOC_NGANHANG
GO
CREATE PROC GET_DS_HOCPHAN_NGANHANG @MANGANHANG INT, @MAGV CHAR(10)
AS
BEGIN
	SELECT HOCPHAN.MAHOCPHAN, TENHOCPHAN FROM CT_GIANGDAY, HOCPHAN 
	WHERE CT_GIANGDAY.MAHOCPHAN = HOCPHAN.MAHOCPHAN
		AND MAGV = @MAGV
		AND CT_GIANGDAY.MAHOCPHAN NOT IN (SELECT MAHOCPHAN FROM CT_NGANHANGCAUHOI WHERE MANGANHANG = @MANGANHANG)
END
GO
	
-- CREATE PROC GET_DS_MONHOC_GIANGVIEN
GO
CREATE PROC GET_DS_HOCPHAN_GIANGVIEN @MAGV CHAR(10)
AS
BEGIN
	SELECT CT_GIANGDAY.MAHOCPHAN, TENHOCPHAN FROM CT_GIANGDAY, HOCPHAN
	WHERE CT_GIANGDAY.MAHOCPHAN = HOCPHAN.MAHOCPHAN AND MAGV = @MAGV
END
GO

-- CREATE PROC GET_DS_NGANHANGCAUHOI_GIANGVIEN
GO
CREATE PROC GET_DS_NGANHANGCAUHOI_GIANGVIEN 
AS
BEGIN
	SELECT CT_NGANHANGCAUHOI.MAGV, TENGV, COUNT(*) AS SOLUONGMON, NGAYCAPNHAT, NGANHANGCAUHOI.MANGANHANG 
	FROM GIANGVIEN, NGANHANGCAUHOI, CT_NGANHANGCAUHOI
	WHERE GIANGVIEN.MAGV = CT_NGANHANGCAUHOI.MAGV
		AND NGANHANGCAUHOI.MANGANHANG = CT_NGANHANGCAUHOI.MANGANHANG
	GROUP BY CT_NGANHANGCAUHOI.MAGV, TENGV, NGAYCAPNHAT, NGANHANGCAUHOI.MANGANHANG
END
GO

-- CREATE PROC GET_DS_CAUHOI_DADUYET
GO
CREATE PROC GET_DS_CAUHOI_DADUYET
AS
BEGIN
	SELECT NGANHANGCAUHOI_DADUYET.MANH, NGANHANGCAUHOI_DADUYET.MAHOCPHAN,
			NGANHANGCAUHOI_DADUYET.MACAUHOI, NOIDUNG, DAPAN1, DAPAN2, DAPAN3, DAPAN4, DAPANDUNG
	FROM NGANHANGCAUHOI_DADUYET, CAUHOI 
	WHERE NGANHANGCAUHOI_DADUYET.MACAUHOI = CAUHOI.MACAUHOI
END
GO

-- CREATE PROC GET_DS_DETHI
GO
CREATE PROC GET_DS_DETHI @MAHOCPHAN CHAR(10)
AS
BEGIN
	SELECT MADETHI, DETHI.MAHOCPHAN, TENHOCPHAN, NGAYTAO, TGLAMBAI, SLCAUHOI, TINHTRANG
	FROM DETHI, HOCPHAN
	WHERE DETHI.MAHOCPHAN = HOCPHAN.MAHOCPHAN
		AND DETHI.MAHOCPHAN = @MAHOCPHAN
END
GO

-- CREATE PROC GET_DS_DETHI_DETHICON
GO
CREATE PROC GET_DS_DETHI_DETHICON @MAHOCPHAN CHAR(10), @MADETHI INT
AS
BEGIN
	SELECT DISTINCT(DETHI.MADETHI), (MADECON), DETHI.MAHOCPHAN, TENHOCPHAN, NGAYTAO, TGLAMBAI, SLCAUHOI, TINHTRANG
	FROM DETHI, CT_DETHI, HOCPHAN
	WHERE DETHI.MADETHI = CT_DETHI.MADETHI AND DETHI.MAHOCPHAN = HOCPHAN.MAHOCPHAN
		AND DETHI.MAHOCPHAN = @MAHOCPHAN AND DETHI.MADETHI = @MADETHI
END
GO

-- CREATE PROC GET_DS_DETHI
GO
CREATE PROC GET_DS_DETHIS
AS
BEGIN
	SELECT MADETHI, DETHI.MAHOCPHAN, TENHOCPHAN, NGAYTAO, TGLAMBAI, SLCAUHOI, TINHTRANG
	FROM DETHI, HOCPHAN
	WHERE DETHI.MAHOCPHAN = HOCPHAN.MAHOCPHAN
END
GO

-- CREATE PROC GET_DS_DETHI_CAUHOI
GO
CREATE PROC GET_DS_DETHI_CAUHOI @MADETHI INT, @MADECON CHAR(10)
AS
BEGIN
	SELECT MADETHI, CT_DETHI.MACAUHOI, NOIDUNG, DAPAN1, DAPAN2, DAPAN3, DAPAN4, DAPANDUNG
	FROM CT_DETHI, CAUHOI
	WHERE CT_DETHI.MACAUHOI = CAUHOI.MACAUHOI
		AND MADETHI = @MADETHI AND MADECON = @MADECON
END
GO

GO
CREATE PROC GET_DS_DETHI_CAUHOI_WORD @MADETHI INT, @MADECON CHAR(10)
AS
BEGIN
	SELECT NOIDUNG, DAPAN1, DAPAN2, DAPAN3, DAPAN4, DAPANDUNG
	FROM CT_DETHI, CAUHOI
	WHERE CT_DETHI.MACAUHOI = CAUHOI.MACAUHOI
		AND MADETHI = @MADETHI AND MADECON = @MADECON
END
GO

-- CREATE PROC GET_DS_SV_HOCPHAN
-- LẤY SINH VIÊN CÓ THAM GIA LỚP HỌC PHẦN MÀ CHƯA THAM GIA THI
GO
CREATE PROC GET_DS_SV_LOPHOCPHAN @MAHOCPHAN CHAR(10)
AS
BEGIN
	SELECT DISTINCT(CT_HOCPHAN.MASV), TENSV, GIOITINH, NGAYSINH, EMAIL, SDT, DIACHI, QUEQUAN, MALOP, HOCPHI
	FROM CT_HOCPHAN, SINHVIEN
	WHERE CT_HOCPHAN.MASV = SINHVIEN.MASV
		AND MAHOCPHAN = @MAHOCPHAN AND CT_HOCPHAN.MASV NOT IN (SELECT DISTINCT(MASV) FROM CATHI, CT_CATHI 
														WHERE CATHI.MACATHI = CT_CATHI.MACATHI
														AND MAHOCPHAN = @MAHOCPHAN AND TINHTRANGTHI = 0)
END
GO

-- CREATE PROC GET_DS_CATHIS
GO
CREATE PROC GET_DS_CATHIS 
AS
BEGIN
	SELECT MACATHI, CATHI.MAHOCPHAN, TENHOCPHAN, MADETHI, MADECON, NGAYTHI, GIOLAMBAI, PHONGTHI
	FROM CATHI, HOCPHAN
	WHERE CATHI.MAHOCPHAN = HOCPHAN.MAHOCPHAN
END
GO

-- CREATE PROC GET_DS_CATHIS_HOCPHAN
GO
CREATE PROC GET_DS_CATHIS_HOCPHAN @MAHOCPHAN CHAR(10)
AS
BEGIN
	SELECT MACATHI, CATHI.MAHOCPHAN, TENHOCPHAN, MADETHI, MADECON, NGAYTHI, GIOLAMBAI, PHONGTHI
	FROM CATHI, HOCPHAN
	WHERE CATHI.MAHOCPHAN = HOCPHAN.MAHOCPHAN AND CATHI.MAHOCPHAN = @MAHOCPHAN
END
GO

-- CREATE PROC GET_DSSV_CATHI
GO
CREATE PROC GET_DSSV_CATHI @MACATHI INT
AS
BEGIN
	SELECT SINHVIEN.MASV, SINHVIEN.TENSV, GIOITINH, NGAYSINH, MALOP
	FROM SINHVIEN, CT_CATHI
	WHERE SINHVIEN.MASV = CT_CATHI.MASV
		AND MACATHI = @MACATHI
END
GO

-- CREATE PROC GET_DSSV_CHUA_THAM_GIA_THI
GO
CREATE PROC GET_DSSV_CHUA_THAM_GIA_THI @MAHOCPHAN CHAR(10)
AS
BEGIN
	SELECT DISTINCT(CT_HOCPHAN.MASV), TENSV, GIOITINH, NGAYSINH, EMAIL, SDT, DIACHI, QUEQUAN, MALOP, HOCPHI
	FROM CT_HOCPHAN, SINHVIEN
	WHERE CT_HOCPHAN.MASV = SINHVIEN.MASV
		AND MAHOCPHAN = @MAHOCPHAN AND CT_HOCPHAN.MASV NOT IN (SELECT DISTINCT(MASV) FROM CATHI, CT_CATHI
																	WHERE CATHI.MACATHI = CT_CATHI.MACATHI 
																	AND MAHOCPHAN = @MAHOCPHAN)
END
GO

-- CREATE PROC GET_DSGV
GO
CREATE PROC GET_DSGV
AS
BEGIN
	SELECT GIANGVIEN.MAGV, TENGV, NGAYSINH, GIOITINH, QUEQUAN, HOCVI, SDT, EMAIL, DIACHI, TENKHOA, TENCHUCVU, GIANGVIEN.MAKHOA, GIANGVIEN.MACHUCVU
	FROM GIANGVIEN, KHOA, CHUCVU
	WHERE GIANGVIEN.MAKHOA = KHOA.MAKHOA AND GIANGVIEN.MACHUCVU = CHUCVU.MACHUCVU
END
GO

-- CREATE PROC GET_DSGV_KHOA
GO
CREATE PROC GET_DSGV_KHOA @MAKHOA CHAR(2)
AS
BEGIN
	SELECT GIANGVIEN.MAGV, TENGV, NGAYSINH, GIOITINH, QUEQUAN, HOCVI, SDT, EMAIL, DIACHI, TENKHOA, TENCHUCVU, GIANGVIEN.MAKHOA, GIANGVIEN.MACHUCVU
	FROM GIANGVIEN, KHOA, CHUCVU
	WHERE GIANGVIEN.MAKHOA = KHOA.MAKHOA AND GIANGVIEN.MACHUCVU = CHUCVU.MACHUCVU AND GIANGVIEN.MAKHOA = @MAKHOA
	AND TENGV != 'admin'
END
GO

-- CREATE PROC GET_DSKHOA
GO
CREATE PROC GET_DSKHOA
AS
BEGIN
	SELECT KHOA.MAKHOA, TENKHOA, COUNT(MAGV) AS SLGV
	FROM KHOA, GIANGVIEN
	WHERE KHOA.MAKHOA = GIANGVIEN.MAKHOA 
	GROUP BY KHOA.MAKHOA, TENKHOA
END
GO

-- CREATE PROC GET_DSHOCPHAN
GO
CREATE PROC GET_DSHOCPHAN
AS
BEGIN
	SELECT MAHOCPHAN, TENHOCPHAN, SOTC, SOTIET_LT, SOTIET_TH, TENKHOA, HOCPHAN.MAKHOA
	FROM HOCPHAN, KHOA
	WHERE HOCPHAN.MAKHOA = KHOA.MAKHOA
END
GO

-- CREATE PROC GET_DSHOCPHAN
GO
CREATE PROC GET_DSHOCPHAN_KHOA @MAKHOA CHAR(2)
AS
BEGIN
	SELECT MAHOCPHAN, TENHOCPHAN, SOTC, SOTIET_LT, SOTIET_TH, TENKHOA, HOCPHAN.MAKHOA
	FROM HOCPHAN, KHOA
	WHERE HOCPHAN.MAKHOA = KHOA.MAKHOA
		AND HOCPHAN.MAKHOA = @MAKHOA
		AND MAHOCPHAN != '0101000000'
END
GO

-- CREATE PROC GET_DSLOPHOC
GO
CREATE PROC GET_DSLOPHOC
AS
BEGIN
	SELECT MALOP, TENLOP, SISO, TENKHOA, LOPHOC.MAKHOA
	FROM LOPHOC, KHOA
	WHERE LOPHOC.MAKHOA = KHOA.MAKHOA
END
GO

-- CREATE PROC GET_DSLOPHOC_KHOA
GO
CREATE PROC GET_DSLOPHOC_KHOA @MAKHOA CHAR(2)
AS
BEGIN
	SELECT MALOP, TENLOP, SISO, TENKHOA, LOPHOC.MAKHOA
	FROM LOPHOC, KHOA
	WHERE LOPHOC.MAKHOA = KHOA.MAKHOA
		AND LOPHOC.MAKHOA = @MAKHOA
END
GO

---- CREATE PROC GET_DSSV_KHOA
--GO
--CREATE PROC GET_DSSV_KHOA @MALOP CHAR(10), @MAKHOA CHAR(2)
--AS
--BEGIN
--	SELECT SINHVIEN.MASV, TENSV, GIOITINH, NGAYSINH, EMAIL, SDT, DIACHI, QUEQUAN, MALOP, HOCPHI
--	FROM SINHVIEN, LOPHOC, CT_HOCPHAN, HOCPHAN
--	WHERE SINHVIEN.MASV = CT_HOCPHAN.MASV 
--		AND HOCPHAN.MAHOCPHAN = CT_HOCPHAN.MAHOCPHAN
--		AND MAKHOA = '01'
--END
--GO
--EXEC GET_DSSV_KHOA '01'


-- CREATE PROC GET_DSSV_HOCPHAN
GO
CREATE PROC GET_DSSV_HOCPHAN @MALOPHOCPHAN CHAR(12)
AS
BEGIN
	SELECT CT_HOCPHAN.MASV, TENSV, GIOITINH, NGAYSINH, EMAIL, SDT, DIACHI, QUEQUAN, MALOP, HOCPHI
	FROM CT_HOCPHAN, SINHVIEN
	WHERE CT_HOCPHAN.MASV = SINHVIEN.MASV
		AND MALOPHOCPHAN = @MALOPHOCPHAN
END
GO

-- CREATE PROC GET_CT_HOCPHAN
GO
CREATE PROC GET_CT_HOCPHAN @MAHOCPHAN CHAR(10)
AS
BEGIN
	SELECT DISTINCT(MALOPHOCPHAN), CT_HOCPHAN.MAGV, THU, TIET, PHONG, NGAYBD, NGAYKT, TENGV
	FROM CT_HOCPHAN, GIANGVIEN
	WHERE CT_HOCPHAN.MAGV = GIANGVIEN.MAGV
		AND MAHOCPHAN = @MAHOCPHAN
END
GO

-- CREATE PROC GET_CT_LOPHOCPHAN
GO
CREATE PROC GET_CT_LOPHOCPHAN @MALOPHOCPHAN CHAR(12)
AS
BEGIN
	SELECT DISTINCT(MALOPHOCPHAN), CT_HOCPHAN.MAGV, THU, TIET, PHONG, NGAYBD, NGAYKT, TENGV
	FROM CT_HOCPHAN, GIANGVIEN
	WHERE CT_HOCPHAN.MAGV = GIANGVIEN.MAGV
		AND MALOPHOCPHAN = @MALOPHOCPHAN
END
GO

-- CREATE PROC GET_DSSV_CHUA_THAMGIA_HOCPHAN
-- LẤY DANH SÁCH SINH VIÊN CỦA KHOA CHƯA THAM GIA CATHI HỌC PHẦN CỦA KHOA
GO
CREATE PROC GET_DSSV_CHUA_THAMGIA_HOCPHAN @MAKHOA CHAR(2), @MALOPHOCPHAN CHAR(12)
AS
BEGIN
	SELECT MASV, TENSV, GIOITINH, NGAYSINH, EMAIL, SDT, DIACHI, QUEQUAN, SINHVIEN.MALOP, HOCPHI
	FROM SINHVIEN, LOPHOC 
	WHERE SINHVIEN.MALOP = LOPHOC.MALOP 
		AND MAKHOA = @MAKHOA
		AND  MASV NOT IN (SELECT MASV FROM CT_HOCPHAN WHERE MALOPHOCPHAN = @MALOPHOCPHAN)
END
GO

-- LẤY DANH SÁCH SINH VIÊN THAM GIA HỌC PHẦN NHƯNG CHƯA THAM GIA CA THI NÀO
GO
CREATE PROC GETDSSVHOCPHANCHUATHI @MAHOCPHAN CHAR(10)
AS
BEGIN
	SELECT DISTINCT(SINHVIEN.MASV), TENSV, GIOITINH, NGAYSINH, EMAIL, SDT, DIACHI, QUEQUAN, SINHVIEN.MALOP, HOCPHI
	FROM SINHVIEN, CT_HOCPHAN
	WHERE SINHVIEN.MASV = CT_HOCPHAN.MASV
		AND MAHOCPHAN = @MAHOCPHAN
		AND SINHVIEN.MASV NOT IN (SELECT DISTINCT(MASV) FROM CT_CATHI, CATHI 
									WHERE CT_CATHI.MACATHI = CATHI.MACATHI 
									AND MAHOCPHAN = @MAHOCPHAN AND TINHTRANGTHI = 0)
END
GO

-- CREATE PROC GETDSSVKHOALOPHP
-- LẤY DANH SÁCH SINH VIÊN CỦA KHOA CHƯA THAM GIA LỚP HỌC PHẦN NÀO CÓ THỨ ĐÓ - TIẾT ĐÓ
GO
CREATE PROC GETDSSVKHOALOPHP @MAKHOA CHAR(2), @THU INT, @TIET CHAR(10)
AS
BEGIN
	SELECT MASV, TENSV, GIOITINH, NGAYSINH, EMAIL, SDT, DIACHI, QUEQUAN, HOCPHI, SINHVIEN.MALOP
	FROM SINHVIEN, LOPHOC
	WHERE SINHVIEN.MALOP = LOPHOC.MALOP AND MAKHOA = @MAKHOA 
		AND MASV NOT IN (SELECT MASV FROM CT_HOCPHAN WHERE THU = @THU AND TIET = @TIET)
END
GO

-- CREATE PROC GETDSCATHI_TRONGNGAY
GO
CREATE PROC GETDSCATHI
AS
BEGIN
	SELECT CATHI.MACATHI, CATHI.MAHOCPHAN, TENHOCPHAN, MADECON, PHONGTHI, GIOLAMBAI, NGAYTHI, COUNT(CT_CATHI.MASV) AS SLSV, TINHTRANG
	FROM CATHI, CT_CATHI, HOCPHAN
	WHERE CATHI.MAHOCPHAN = HOCPHAN.MAHOCPHAN
		AND CATHI.MACATHI = CT_CATHI.MACATHI
		AND TINHTRANG = 1
	GROUP BY CATHI.MACATHI, CATHI.MAHOCPHAN, TENHOCPHAN, MADECON, PHONGTHI, GIOLAMBAI, NGAYTHI, TINHTRANG	
END
GO

GO
CREATE PROC GETDSCATHINGAY @NGAYTHI DATE
AS
BEGIN
	SELECT CATHI.MACATHI, CATHI.MAHOCPHAN, TENHOCPHAN, MADECON, PHONGTHI, GIOLAMBAI, NGAYTHI, COUNT(CT_CATHI.MASV) AS SLSV, TINHTRANG
	FROM CATHI, CT_CATHI, HOCPHAN
	WHERE CATHI.MAHOCPHAN = HOCPHAN.MAHOCPHAN
		AND CATHI.MACATHI = CT_CATHI.MACATHI
		AND TINHTRANG = 1 AND NGAYTHI = @NGAYTHI
	GROUP BY CATHI.MACATHI, CATHI.MAHOCPHAN, TENHOCPHAN, MADECON, PHONGTHI, GIOLAMBAI, NGAYTHI, TINHTRANG	
END
GO

-- CREATE PROC GETDSCATHI_PHONG_TIET_NGAY
GO
CREATE PROC GETDSCATHI_PHONG_TIET_NGAY @PHONG NVARCHAR(20), @GIOLAMBAI NVARCHAR(10), @NGAYTHI DATE
AS
BEGIN
	SELECT CATHI.MACATHI, CATHI.MAHOCPHAN, TENHOCPHAN, MADECON, PHONGTHI, GIOLAMBAI, NGAYTHI, COUNT(CT_CATHI.MASV) AS SLSV, TINHTRANG
	FROM CATHI, CT_CATHI, HOCPHAN
	WHERE CATHI.MAHOCPHAN = HOCPHAN.MAHOCPHAN
		AND CATHI.MACATHI = CT_CATHI.MACATHI
		AND TINHTRANG = 1 AND PHONGTHI = @PHONG AND GIOLAMBAI = @GIOLAMBAI AND NGAYTHI = @NGAYTHI
	GROUP BY CATHI.MACATHI, CATHI.MAHOCPHAN, TENHOCPHAN, MADECON, PHONGTHI, GIOLAMBAI, NGAYTHI, TINHTRANG	
END
GO

-- CREATE PROC GETDSCATHI_PHONG_TIET
GO
CREATE PROC GETDSCATHI_PHONG_TIET @PHONG NVARCHAR(20), @GIOLAMBAI NVARCHAR(10)
AS
BEGIN
	SELECT CATHI.MACATHI, CATHI.MAHOCPHAN, TENHOCPHAN, MADECON, PHONGTHI, GIOLAMBAI, NGAYTHI, COUNT(CT_CATHI.MASV) AS SLSV, TINHTRANG
	FROM CATHI, CT_CATHI, HOCPHAN
	WHERE CATHI.MAHOCPHAN = HOCPHAN.MAHOCPHAN
		AND CATHI.MACATHI = CT_CATHI.MACATHI
		AND TINHTRANG = 1 AND PHONGTHI = @PHONG AND GIOLAMBAI = @GIOLAMBAI
	GROUP BY CATHI.MACATHI, CATHI.MAHOCPHAN, TENHOCPHAN, MADECON, PHONGTHI, GIOLAMBAI, NGAYTHI, TINHTRANG	
END
GO

-- CREATE PROC GETDSBAITHI
GO
CREATE PROC GETDSBAITHI @MACATHI INT
AS
BEGIN
	SELECT CT_CATHI.MASV, SINHVIEN.TENSV, NGAYSINH, GIOITINH, MALOP, TINHTRANG, GIONOPBAI, MABAITHI
	FROM CT_CATHI, SINHVIEN, BAITHI
	WHERE CT_CATHI.MASV = SINHVIEN.MASV
		AND BAITHI.MASV = CT_CATHI.MASV
		AND BAITHI.MACATHI = 1003
END
GO

-- CREATE PROC GETDSSVTHAMGIA
GO
CREATE PROC GETDSSVTHAMGIA @MACATHI INT
AS
BEGIN
	SELECT DISTINCT(CT_CATHI.MASV), SINHVIEN.TENSV, NGAYSINH, GIOITINH, MALOP, TINHTRANG, GIONOPBAI, MABAITHI, DIEM
	FROM (CT_CATHI INNER JOIN SINHVIEN ON CT_CATHI.MASV = SINHVIEN.MASV) 
		LEFT JOIN BAITHI ON CT_CATHI.MASV = BAITHI.MASV 
	WHERE CT_CATHI.MACATHI = @MACATHI
END
GO

GO
CREATE PROC GETDSSVTHAMGIAEXCEL @MACATHI INT
AS
BEGIN
	SELECT DISTINCT(CT_CATHI.MASV), SINHVIEN.TENSV, GIOITINH, MALOP, TINHTRANG, GIONOPBAI, DIEM
	FROM (CT_CATHI INNER JOIN SINHVIEN ON CT_CATHI.MASV = SINHVIEN.MASV) 
		LEFT JOIN BAITHI ON CT_CATHI.MASV = BAITHI.MASV 
	WHERE CT_CATHI.MACATHI = @MACATHI
END
GO

-- CREATE PROC GETDSCAUHOIBAITHI
GO
CREATE PROC GETDSCAUHOIBAITHI @MABAITHI INT
AS
BEGIN
	SELECT CT_BAITHI.MACAUHOI, NOIDUNG, DAPAN1, DAPAN2, DAPAN3, DAPAN4, DAPANDUNG, CAUTRALOI
	FROM CT_BAITHI, CAUHOI
	WHERE CT_BAITHI.MACAUHOI = CAUHOI.MACAUHOI
		AND MABAITHI = @MABAITHI
END
GO